export enum CountryCode {
  IN = 'India',
  US = 'United States',
  GB = 'United Kingdom',
  FR = 'France',
  DE = 'Germany',
  ES = 'Spain',
  IT = 'Italy',
  CA = 'Canada',
  AU = 'Australia',
  NL = 'Netherlands',
  PL = 'Poland',
  BR = 'Brazil',
  RU = 'Russia',
  JP = 'Japan',
  KR = 'South Korea',
  CN = 'China',
  ZA = 'South Africa',
  MX = 'Mexico',
  AR = 'Argentina',
  SE = 'Sweden',
  NO = 'Norway',
  DK = 'Denmark',
  FI = 'Finland',
}
